import type { Metadata } from 'next'
import './globals.css'
import Header from '@/components/common/Header'
import Footer from '@/components/common/Footer'
import SubHeader from '@/components/common/SubHeader'

export const metadata: Metadata = {
  title: 'MKは勉強したい',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <Header />
        <SubHeader />
        <div className='z-10'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
